** 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?



1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Ans:
NumPy is ideal for handling large amounts of homogeneous (same-type) data, offering significant improvements in speed and memory efficiency. It also provides high-level syntax for a wide range of numerical operations, making it a powerful tool for scientific computing and data processing on the CPU.
Efficient Handling of Large Arrays and Matrices.

Faster Exection:
        import numpy as np
        a = np.array([1, 2, 3])
        b = np.array([4, 5, 6])
        result = a + b  # Element-wise addition
            
Efficient Memory Usage:

NumPy arrays are more memory-efficient than Python’s native lists. They store data in contiguous blocks of memory, making data access faster. Additionally, NumPy arrays require less memory because they store data as fixed types (e.g., int32, float64), unlike Python lists, which store objects.

Broadcasting for Flexible Operations:
NumPy’s broadcasting feature allows arrays of different shapes to be combined in operations without copying or expanding them, as long as they are compatible.
    a = np.array([1, 2, 3])
    b = 5
    result = a + b  # Scalar is broadcast to each element of the array
    
Support for Multidimensional Arrays:

While Python lists are limited to 1D or nested lists for multi-dimensional data, NumPy handles multi-dimensional arrays directly. This is critical for numerical and scientific tasks such as image processing, machine learning, or simulations.

    array_2d = np.array([[1, 2], [3, 4]])

 Element-wise Operations:
 In NumPy, mathematical operations like addition, subtraction, multiplication, etc., can be applied element-wise to entire arrays with a single operation.


2.Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
Ans. In NumPy, both np.mean() and np.average() are used to calculate the average of array elements, but they differ in functionality and use cases.

    Basic Functionality:

    np.mean(): Calculates the arithmetic mean (simple average) of the elements in an array.
    np.average(): Calculates the weighted average of the array elements if weights are provided. Without weights, it computes the arithmetic mean, 
                    similar to np.mean().

    
    Syntax:

    np.mean
    np.mean(a, axis=None, dtype=None, out=None, keepdims=False)


    np.average()
    np.average(a, axis=None, weights=None, returned=False)

    Weights Handling:

    np.mean(): Does not support weights; it always calculates a simple arithmetic mean.
    np.average(): Can calculate a weighted average when the weights parameter is provided. The weights determine the contribution of each element to the
                    total average.

    Example:
        import numpy as np
        data = np.array([1, 2, 3, 4])
        weights = np.array([1, 2, 3, 4])
        
        np.mean(data)  # Output: 2.5
        np.average(data, weights=weights)  # Output: 3.0 (Weighted average)


    Return of Weights Sum:

    np.average(data, weights=weights, returned=True)
    # Output: (3.0, 10.0)  # 3.0 is the weighted average, 10.0 is the sum of weights

    Axis Handling:

    Both functions support the axis argument, allowing you to calculate the mean or average along a specified axis of a multi-dimensional array.
    Example:

    arr = np.array([[1, 2], [3, 4]])
    np.mean(arr, axis=0)  # Output: array([2., 3.])
    np.average(arr, axis=0)  # Output: array([2., 3.])


    Performance Considerations:

    np.mean(): Faster and simpler for calculating the arithmetic mean, since it doesn’t handle weights.
    np.average(): Slightly slower due to the overhead of handling the weights argument, even if weights aren’t provided.




     When to Use np.mean():

    Simple Arithmetic Mean: If you need to compute the average of all elements in an array and each element has equal importance, use np.mean().
    
    Example: Calculating the average temperature for a week (where each day has equal importance).
    Reason: It’s simpler, faster, and doesn’t require the overhead of handling weights.
    Performance Priority: When performance is a concern and you don’t need weighted averages, np.mean() is typically faster than np.average() because 
    it doesn’t process weights.

    When to Use np.average():

        Weighted Average: Use np.average() when you need to compute a weighted average, meaning different elements in the array contribute differently          to the final result.
    
        Example: Calculating a student’s final grade where assignments, quizzes, and exams have different weightages (e.g., assignments = 30%, exams =            70%).
        Reason: np.mean() does not support weights, so np.average() is necessary to handle weighted contributions.
        Need Sum of Weights: If you also need to return the sum of the weights along with the average, np.average() can return both when you set                returned=True.
        
        Example: In financial applications where you calculate weighted returns, knowing the sum of weights can be useful.

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
Ans.
Using Array Slicing :This is the simplest method for reversing a NumPy array. The slice [::-1] can reverse the elements along a particular axis.

Reversing a 1D Array:

    import numpy as np
    
    arr_1d = np.array([1, 2, 3, 4, 5])
    reversed_1d = arr_1d[::-1]
    print(reversed_1d)  # Output: [5 4 3 2 1]

Reversing a 2D Array Along Different Axes:

    arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    
    # Reverse rows (axis=0)
    reversed_rows = arr_2d[::-1, :]
    print(reversed_rows)
    # Output:
    # [[7 8 9]
    #  [4 5 6]
    #  [1 2 3]]
    
    # Reverse columns (axis=1)
    reversed_columns = arr_2d[:, ::-1]
    print(reversed_columns)
    # Output:
    # [[3 2 1]
    #  [6 5 4]
    #  [9 8 7]]
    
    # Reverse both rows and columns
    reversed_both = arr_2d[::-1, ::-1]
    print(reversed_both)
    # Output:
    # [[9 8 7]
    #  [6 5 4]
    #  [3 2 1]]                                                                      
                                                                                          

4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
    in memory management and performance.
Ans. We can determine the data type of elements in a NumPy array using the dtype attribute. This attribute provides information about the type of
    elements stored in the array, such as int32, float64, or bool

        import numpy as np
        
        # Create an example array
        arr = np.array([1, 2, 3, 4])
        
        # Determine the data type of elements
        print(arr.dtype)

        #Output is int64

    Memory Management:Each data type in NumPy has a specific size in memory, which is measured in bytes. Choosing the appropriate data type allows you
                        to manage memory efficiently, particularly when working with large datasets.

          Each data type requires a different amount of memory to store an element. For example:

            int32 uses 4 bytes (32 bits).
            int64 uses 8 bytes (64 bits).
            float32 uses 4 bytes.
            float64 uses 8 bytes.                       

    By selecting the smallest data type that fits your data, you can significantly reduce memory usage. This is critical when dealing with large arrays.

    import numpy as np

    # Using float64 (8 bytes per element)
    arr1 = np.array([1.0, 2.0, 3.0], dtype=np.float64)
    print(arr1.nbytes)  # Output: 24 bytes
    
    # Using float32 (4 bytes per element)
    arr2 = np.array([1.0, 2.0, 3.0], dtype=np.float32)
    print(arr2.nbytes)  # Output: 12 bytes

     Performance Optimization:

    Data types also influence the speed of numerical operations. Smaller data types are processed faster because they use fewer resources
                (e.g., less memory bandwidth). Additionally, different data types can be optimized differently by modern processors.

        arr_float32 = np.array([1.0, 2.0, 3.0], dtype=np.float32)
        arr_float64 = np.array([1.0, 2.0, 3.0], dtype=np.float64)
        
        # Timing the operations
        %timeit arr_float32 * 2  # Faster
        %timeit arr_float64 * 2  # Slower


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
Ans:
    Definition:An ndarray (N-dimensional array) is the core data structure in NumPy, representing a grid of values (usually of the same data type) and
    supporting multi-dimensional data. It is highly optimized for numerical computations and forms the foundation for scientific and numerical computing
        in Python.
                                                                                                                 

    Key FeAatures:

    (a) Homogeneous Data Type:

        Every element in an ndarray has the same data type (e.g., integers, floats, booleans). This makes it more efficient than Python lists, which 
        can hold elements of different types.
                                                                                                                 
    (b) Multidimensional:                                                                                                           
          ndarray can handle arrays of arbitrary dimensions (1D, 2D, 3D, etc.). This allows for powerful manipulations in multiple dimensions for
                matrices, tensors, or higher-dimensional data.                                                                                                       

         The number of dimensions is given by the ndim attribute, and the shape (size of each dimension) is given by the shape attribute.   

     (c) Efficient Memory Usage:
        ndarray objects use contiguous blocks of memory, allowing for fast access and manipulation of data. This is different from Python lists, which
              store elements as separate objects.    

         NumPy allows specifying the data type (dtype) to optimize memory usage for specific needs (e.g., float32, int64). 
                                                                                                                             
     (d) Broadcasting:
          NumPy arrays support broadcasting, which allows operations between arrays of different shapes in a vectorized way. This means element-wise 
                                                                                                                             operations can be applied without explicitly looping over array elements, boosting performance.                                                                                                                   
                                                                                                                             
                                                                                                                             
                                                                                                                             

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
Ans.In NumPy, the vstack() and hstack() functions are used to stack arrays vertically and horizontally, respectively.

(A)np.vstack() : np.vstack() stacks arrays vertically, meaning it concatenates arrays along the first axis (axis 0). The arrays being stacked must have
    the same number of columns (second dimension) but can have a different number of rows (first dimension).
    import numpy as np
    
    # Define two 1D arrays
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    
    # Vertical stack (converts 1D arrays to 2D)
    vstack_result_1d = np.vstack((arr1, arr2))
    print(vstack_result_1d)

  (B) np.hstack() :  np.hstack() stacks arrays horizontally, meaning it concatenates arrays along the second axis (axis 1). The arrays being stacked 
    must have the same number of rows (first dimension) but can have a different number of columns (second dimension).
    
    import numpy as np
    
    # Define two 1D arrays
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    
    # Horizontal stack (concatenates 1D arrays into a single 1D array)
    hstack_result_1d = np.hstack((arr1, arr2))
    print(hstack_result_1d)


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
Ans.
    Differences Between fliplr() and flipud() in NumPy:
    In NumPy, fliplr() and flipud() are two array manipulation functions used to reverse the elements of an array along different axes. Their effects
    vary depending on the array's dimensions (2D, 3D, etc.).

    np.fliplr():  fliplr() flips an array horizontally, reversing the order of elements along the columns (axis 1). It works only for arrays with two or 
    more dimensions (2D, 3D, etc.).It reverses the order of the columns, so the leftmost column becomes the rightmost, the second column becomes 
        second-to-last, and so on.

        import numpy as np

        # Define a 2D array
        arr = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])
        
        # Flip left to right
        result_fliplr = np.fliplr(arr)
        print(result_fliplr)
        #OUTPUT
         [[3 2 1]
         [6 5 4]
         [9 8 7]]
                         
     np.flipud() : flipud() flips an array vertically, reversing the order of elements along the rows (axis 0). Like fliplr(), it works only for 
                 arrays with two or more dimensions. It reverses the order of the rows, so the top row becomes the bottom, the second row becomes 
                 second-to-last, and so on.

        import numpy as np
        
        # Define a 2D array
        arr = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])
        
        # Flip up to down
        result_flipud = np.flipud(arr)
        print(result_flipud)
      #OUTPUT
         [[7 8 9]
         [4 5 6]
         [1 2 3]]
                      
                     


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
Ans. Functionality of np.array_split() in NumPy:
    The np.array_split() method is used to split an array into multiple sub-arrays. It works similarly to np.split(), but with one key advantage: it can
    handle uneven splits. This means that when the array cannot be evenly divided, array_split() ensures that some of the resulting sub-arrays will have
    more elements than others, distributing the extra elements as needed.

    Key Features of np.array_split():-
    Splitting Along an Axis: By default, array_split() splits the array along axis 0 (the first axis, which corresponds to rows in a 2D array). However,
    you can specify a different axis using the axis argument.
    Handles Uneven Splits: Unlike np.split(), which raises an error if the array cannot be split into equal parts, array_split() adjusts for uneven 
    splits by distributing the extra elements across the sub-arrays.
                                                                                                                                        
    Output: It returns a list of sub-arrays. The number of sub-arrays is determined by the second argument (either an integer specifying the number of
    splits or a list of indices where the splits should occur).

    Syntax: numpy.array_split(array, indices_or_sections, axis=0)





10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
Ans.

    Vectorization:
    Vectorization refers to the process of converting operations that are typically performed in a loop into array operations. This means that instead 
    of applying a function element-wise with explicit loops, you can perform the operation on entire arrays at once.Vectorized operations leverage 
    low-level optimizations in NumPy and often utilize underlying C and Fortran libraries. This results in significantly faster computations compared 
    Code that uses vectorized operations is usually shorter and more readable. This leads to cleaner and more maintainable code.to traditional for-loops
    in Python.Code that uses vectorized operations is usually shorter and more readable. This leads to cleaner and more maintainable code.

    import numpy as np

    # Without vectorization (using loops)
    a = np.array([1, 2, 3, 4])
    b = np.array([5, 6, 7, 8])
    result = np.zeros_like(a)
    for i in range(len(a)):
        result[i] = a[i] + b[i]
    
    # With vectorization
    result = a + b  # This is much faster and more readable

    Broadcasting:
    Broadcasting is a powerful feature in NumPy that allows operations to be performed on arrays of different shapes. When the shapes of the arrays do      not match, NumPy automatically expands (or "broadcasts") the smaller array across the larger array so that they have compatible shapes for the          operation.

    import numpy as np

    # Example of broadcasting
    a = np.array([[1], [2], [3]])  # Shape (3, 1)
    b = np.array([4, 5, 6])         # Shape (3,)
    
    # The shapes are compatible for broadcasting
    result = a + b  # Result shape will be (3, 3)


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
Ans.
    Concepts of Vectorization and Broadcasting in NumPy:
    Both vectorization and broadcasting are key concepts in NumPy that significantly improve performance by enabling efficient, element-wise operations 
    on arrays without the need for explicit loops. They allow NumPy to leverage the low-level, optimized C code under the hood, leading to faster
    computation, especially with large datasets.

    1. Vectorization in NumPy
        Vectorization refers to the process of applying operations to entire arrays (vectors, matrices, or higher-dimensional tensors) at once, rather
than iterating over individual elements with loops. It converts iterative operations into array-level operations, leveraging NumPy’s underlying optimized
    C and Fortran implementations.

         import numpy as np

        arr = np.array([1, 2, 3, 4])
        result = []
        
        # Without vectorization (explicit loop)
        for i in arr:
            result.append(i * 2)
        
        print(result)
        #output
        [2, 4, 6, 8]

    Broadcasting in NumPy:
    Broadcasting is a mechanism that allows NumPy to perform element-wise operations on arrays of different shapes by automatically "stretching" or 
    expanding the smaller array to match the shape of the larger array. This avoids creating redundant copies of the data, leading to efficient memory
    usage and faster operations.

    Use Cases:
    When performing operations between two arrays, NumPy compares their shapes. It starts by comparing the trailing (last) dimensions and works its way forward. Two dimensions are compatible for broadcasting if:

    They are equal, or
    One of them is 1.
    If a dimension is 1, NumPy "stretches" it to match the other dimension, effectively repeating its values to perform the operation.

    import numpy as np

    # Define two arrays of different shapes
    arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
    arr2 = np.array([10, 20, 30])            # Shape (3,)
    
    # Perform element-wise addition
    result = arr1 + arr2
    print(result)


In [11]:
import numpy as np

#11. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
#Ans.
random_array = np.random.randint(1, 101, size=(3, 3))
random_array

# Interchange rows and columns (transpose the matrix)
transposed_array = random_array.T

random_array, transposed_array

12. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
Ans. 
    # Generating a 1D NumPy array with 10 elements
    array_1d = np.random.randint(1, 101, size=10)
    
    # Reshaping it into a 2x5 array
    array_2x5 = array_1d.reshape(2, 5)
    
    # Reshaping it into a 5x2 array
    array_5x2 = array_1d.reshape(5, 2)
    
    array_1d, array_2x5, array_5x2


13. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
Ans.
    # Create a 4x4 NumPy array with random float values
    array_4x4 = np.random.rand(4, 4)
    
    # Add a border of zeros around the array
    array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
    
    array_4x4, array_with_border


14. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
Ans.
    # Creating an array of integers from 10 to 60 with a step of 5
    array_step = np.arange(10, 61, 5)
    array_step


15. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each
    element.
Ans.
    # Creating a NumPy array of strings
    string_array = np.array(['python', 'numpy', 'pandas'])
    
    # Applying different case transformations
    uppercase_array = np.char.upper(string_array)
    lowercase_array = np.char.lower(string_array)
    titlecase_array = np.char.title(string_array)
    
    string_array, uppercase_array, lowercase_array, titlecase_array



16. Generate a NumPy array of words. Insert a space between each character of every word in the array.
Ans.
    # Creating a NumPy array of words
    words_array = np.array(['python', 'numpy', 'pandas'])
    
    # Inserting a space between each character of every word
    spaced_words_array = np.char.join(' ', words_array)
    
    spaced_words_array


17. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
Ans.
        # Creating two 2D NumPy arrays
        array1 = np.random.randint(1, 10, size=(2, 2))
        array2 = np.random.randint(1, 10, size=(2, 2))
        
        # Performing element-wise operations
        addition = array1 + array2
        subtraction = array1 - array2
        multiplication = array1 * array2
        division = array1 / array2
        
        array1, array2, addition, subtraction, multiplication, division


18. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
Ans.
    # Creating a 5x5 identity matrix
    identity_matrix = np.eye(5)
    
    # Extracting the diagonal elements
    diagonal_elements = np.diagonal(identity_matrix)
    
    identity_matrix, diagonal_elements


19. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array1.
Ans.

        # Generate a NumPy array of 100 random integers between 0 and 1000
        random_integers = np.random.randint(0, 1001, size=100)
        
        # Function to check for prime numbers
        def is_prime(n):
            if n <= 1:
                return False
            for i in range(2, int(n**0.5) + 1):
                if n % i == 0:
                    return False
            return True
        
        # Finding and displaying all prime numbers in the array
        prime_numbers = np.array([num for num in random_integers if is_prime(num)])
        
        random_integers, prime_numbers
        


20. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
Ans.
        # Creating a NumPy array representing daily temperatures for a month (30 days)
        daily_temperatures = np.random.uniform(low=15, high=35, size=30)  # Temperatures between 15 and 35 degrees
        
        # Reshape the array to represent weeks (4 weeks and 2 extra days)
        weekly_temperatures = daily_temperatures.reshape(4, 7)  # 4 weeks of 7 days
        
        # Calculate weekly averages
        weekly_averages = np.mean(weekly_temperatures, axis=1)
        
        daily_temperatures, weekly_averages
